# -*- coding: utf-8 -*-
"""While 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1wMca__9SBFz5QV5DlnPp0tSxvZlAII

1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido.
"""

nota =  float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor valido: "))
print("sucesso")

"""Faça um programa while que calcule o mostre a média aritmética de N notas."""

n = int(input("Digite quantas notas deseja inserir: "))
i = 0
soma = 0
while i < n:
  nota = float(input("Digite a nota: "))
  soma += nota
  i += 1
media = soma / n
print("A média das notas é: ", media)

"""Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.
"""

nome = input("Digite o nome de usuario: ")
senha = input("Digite sua senha: ")

while nome == senha:
  print("senha invalida")
  nome = input("Digite o nome de usuario valido: ")
  senha = input("Digite sua senha valida: ")
print("sucesso")

"""Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.
"""

i = 1997
salario = 1000 + 1000 * 0.015
while i <= 2023:
  salario += salario * 0.015 * 2
  i += 1
print(salario)

"""Faça um programa que leia e valide as seguintes informações: Nome: maior que 3 caracteres; Idade: entre 0 e 150; Salário: maior que zero; Sexo: 'f' ou 'm'; Estado Civil: 's', 'c', 'v', 'd';"""

matheus = input("Digite o nome: ")
while len(matheus) <= 3:
  matheus = input("Nome invalido. Digite o nome novamente: ")

idade = int(input("Digite a idade: "))
while idade < 0 or idade > 150:
  idade = int(input("Idade invalida. Digite a idade novamente: "))

salario = float(input("Digite o salário: "))
while salario <= 0:
  salario = float(input("Salário invalido. Digite o salário novamente: "))

sexo = input("Digite o sexo (f/m): ")
while sexo != 'f' and sexo != 'm':
  sexo = input("Sexo invalido. Digite o sexo novamente (f/m): ")

estado_civil = input("Digite o estado civil (s/c/v/d): ")
while estado_civil != 's' and estado_civil != 'c' and estado_civil != 'v' and estado_civil != 'd':
  estado_civil = input("Estado civil invalido. Digite o estado civil novamente (s/c/v/d): ")

print("Dados validados com sucesso!")

"""Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

populacao_a = 80000
populacao_b = 200000
taxa_a = 1.03
taxa_b = 1.015
anos = 0
while populacao_a < populacao_b:
  populacao_a *= taxa_a
  populacao_b *= taxa_b
  anos += 1
print(anos)

"""Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120
"""

numero = int(input("Digite um número inteiro: "))
fatorial = 1
i = 2
while i <= numero:
  fatorial *= i
  i += 1
print(f"O fatorial de {numero} é {fatorial}")

"""Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados.
"""