# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HANi_Na4MwQfuTZD8BCcTXeHxDvLQ3W
"""

nota =  float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor valido: "))
print("sucesso")

nome = input("Digite o nome de usuario: ")
senha = input("Digite sua senha: ")

while nome == senha:
  print("senha invalida")
  nome = input("Digite o nome de usuario valido: ")
  senha = input("Digite sua senha valida: ")
print("sucesso")

numero = 0
while numero >= 0 and numero <= 9:
 numero += 1
 print(numero)

"""Escreva um programa que imprima os números pares de 1 a 20."""

# Inicializa a variável 'numero' com o valor 2
numero = 0
# Entra em um loop while enquanto 'numero' for menor ou igual
while numero >= 0 and numero <= 19:
  numero += 2
  print(numero)

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números de 1 até esse número.
"""

numero = int(input("insira um numero"))

contador = 1

while contador <= numero:
  print(contador)
  contador += 1

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números pares de 2 até esse número.
"""

numero = int(input("digite um numero"))

contador = 0

while contador <= numero:
  print(contador)
  contador += 2

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima a tabuada desse número até 10.
"""

numero = int(input("por favor, digite um numero: "))

contador = 1

while contador <=10:
  resultado = numero * contador
  print(f"{numero} X {contador} = {resultado}")
  contador +=1

"""Escreva um programa que solicite ao usuário que insira uma senha. O
programa deve continuar solicitando a senha até que o usuário insira a senha
correta.
"""

senha = input("Digite sua senha: ")

sen = senha

while senha == sen:
  print("senha invalida")
  senha = input("Digite sua senha valida: ")
print("sucesso")

"""Escreva um programa que calcule a média de uma lista de números fornecida
pelo usuário.
"""

num = float()